---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kontain-faas-server
  namespace: kontain
spec:
  selector:
    matchLabels:
      kontain: faas-server
  template:
    metadata:
      labels:
        kontain: faas-server
    spec:
      containers:
      - name: kontain-faas-server
        image: kontain-faas-server:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
